✨Add Death module
NextCitizens/ncs_core pull request #171
Opened 2022-06-05 23:38 UTC by LQuatre

2022-06-06 06:52 UTC, CsokiHUN commented on src/api/player/server/revive.lua
> +	}
why not use vector3?

2022-06-06 07:06 UTC, CsokiHUN requested changes
i checked this feature, please check my suggestions

2022-06-06 07:06 UTC, CsokiHUN commented on src/modules/players/server/events/onPlayerDeath.lua
> +        end
```suggestion
if (NetworkIsPlayerActive(_src)) then
  local PlayerPed <const> = GetPlayerPed(_src)

  if IsPedFatallyInjured(PlayerPed) and not NCSisDead then
      waitTime = 10
      NCSisDead = true

      local SourceKillerEntity <const>, SourceDeathCause <const> = GetPedSourceOfDeath(PlayerPed)
      local SourceKillerClientId <const> = NetworkGetPlayerIndexFromPed(SourceKillerEntity)
      local PlayerDeathCoords <const> = GetEntityCoords(PlayerPed)

      if SourceKillerEntity ~= _src and SourceKillerClientId and NetworkIsPlayerActive(SourceKillerEntity) then
          local PlayerKillerCoords <const> = GetEntityCoords(SourceKillerEntity)
          local distance <const> = #(PlayerDeathCoords - PlayerKillerCoords)

          local PlayerDeathData = {
              ["PlayerDeathCoords"] = PlayerDeathCoords,
              ["PlayerDeathCause"] = SourceDeathCause,
              ["PlayerDeathTime"] = GetGameTimer(),
              ["KilledByPlayer"] = SourceKillerEntity,
              ["KillerClientId"] = SourceKillerClientId,
              ["KilledByPlayerCoords"] = PlayerKillerCoords,
              ["Distance"] = API_Maths.round(distance, 1)
          }

          NCSPlayer.setDeathStatus(_src, NCSisDead, PlayerDeathData)
      else
          local PlayerDeathData = {
              ["PlayerDeathCoords"] = PlayerDeathCoords,
              ["PlayerDeathCause"] = SourceDeathCause,
              ["PlayerDeathTime"] = GetGameTimer(),
              ["KilledByPlayer"] = false
          }

          NCSPlayer.setDeathStatus(_src, NCSisDead, PlayerDeathData)
      end
  elseif not IsPedFatallyInjured(PlayerPed) and NCSisDead then
      waitTime = 0
      NCSisDead = false
  end
end
```

2022-06-06 07:06 UTC, CsokiHUN commented on src/class/NCSPlayer/server/functions/setDeathStatus.lua
> +    })
```suggestion
API_Database:query("UPDATE ncs_players SET is_dead = @is_dead WHERE player_identifier = @player_identifier ", {
    ["@is_dead"] = (DeadStatus and 1 or 0),
    ["@player_identifier"] = API_Player:getIdentifier(source),
})
```

2022-06-06 07:06 UTC, CsokiHUN commented on src/api/player/server/revive.lua
> +	}
```suggestion
local formattedCoords = vector3(
    API_Maths.round(coords.x, 1),
    API_Maths.round(coords.y, 1),
    API_Maths.round(coords.z, 1),
)
```

2022-06-06 08:07 UTC, MoskalykA requested changes
Please make the changes to a @CsokiHUN

2022-06-06 08:12 UTC, LQuatre commented
Thanks, I did this when I was extremely tired,

i will rework all of this, some functions was not used

2022-06-06 10:16 UTC, MoskalykA requested changes
I didn't report everything but there are a lot of things to review, please test your code, use a syntax more consistent with the project

2022-06-06 10:16 UTC, MoskalykA commented on src/api/player/client/spawn.lua
> +        API_Ped:setInvincible(ped, false)
Utility ?

2022-06-06 10:16 UTC, MoskalykA commented on src/api/player/server/revive.lua
> +function API_Player:revive(PlayerId)
Syntax not correct, coords defined?

2022-06-06 10:16 UTC, MoskalykA commented on src/class/NCSPlayer/server/functions/minify.lua
> +        deathData = self.deathData or false
Application ?

2022-06-06 10:16 UTC, MoskalykA commented on src/class/NCSPlayer/server/functions/setDeathStatus.lua
> +---@param self NCSPlayer
```suggestion
---@param self NCSPlayer
---@public
```

2022-06-06 20:24 UTC, CsokiHUN requested changes

2022-06-06 20:24 UTC, CsokiHUN commented on src/localization/locales/lang_hu.lua
> +    ERROR_PLAYER_NOT_DEAD = "Nem vagy még halott.",
```suggestion
    ERROR_PLAYER_NOT_DEAD = "Játékos nem halott.",
```

2022-06-07 00:06 UTC, LQuatre commented
I have to put some pr toi fix some error

2022-06-07 07:14 UTC, LQuatre commented
@MoskalykA you can review now

2022-06-07 17:39 UTC, CsokiHUN requested changes

2022-06-07 17:39 UTC, CsokiHUN commented on src/core/events/client/kill.lua
> +    local playerPed = GetPlayerPed(-1)
```suggestion
    local playerPed <const> = PlayerPedId()
```

2022-06-07 17:44 UTC, CsokiHUN requested changes

2022-06-07 17:44 UTC, CsokiHUN commented on src/class/NCSCharacter/server/_constructor.lua
> +        end)
```suggestion
        API_Database:single("SELECT is_dead FROM ncs_players_characters WHERE character_id = @character_id", {
          ["@character_id"] = self.id,
        }, function(row)
          self.isDead = row.is_dead
        end)
```

2022-06-07 17:44 UTC, CsokiHUN commented on src/class/NCSCharacter/server/functions/save.lua
> +    API_Database:query("UPDATE ncs_players_characters SET skin = @skin WHERE character_id = @character_id", {
```suggestion
    API_Database:update("UPDATE ncs_players_characters SET skin = @skin WHERE character_id = @character_id", {
```

2022-06-07 17:44 UTC, CsokiHUN commented on src/class/NCSPlayer/server/_constructor.lua
> +        API_Database:query("SELECT role_identifier FROM ncs_players WHERE player_identifier = @player_identifier", {
```suggestion
        API_Database:single("SELECT role_identifier FROM ncs_players WHERE player_identifier = @player_identifier", {
```

2022-06-07 17:44 UTC, CsokiHUN commented on src/class/NCSPlayer/server/_constructor.lua
>              local row <const> = rows[1]
```suggestion
        }, function(row)
```

2022-06-07 17:44 UTC, CsokiHUN commented on src/class/NCSPlayer/server/functions/save.lua
>      API_Database:query("UPDATE ncs_players SET role_identifier = @role_identifier WHERE player_identifier = @player_identifier", {
```suggestion
    API_Database:update("UPDATE ncs_players SET role_identifier = @role_identifier WHERE player_identifier = @player_identifier", {
 ```

2022-06-07 17:48 UTC, MoskalykA commented on src/class/NCSCharacter/server/_constructor.lua
> +        end)
Use async ?

2022-06-07 17:49 UTC, MoskalykA commented on src/class/NCSPlayer/server/_constructor.lua
>              local row <const> = rows[1]
I don't think is good

2022-06-07 17:50 UTC, MoskalykA commented
Infinite loading

2022-06-07 17:51 UTC, CsokiHUN commented on src/class/NCSPlayer/server/_constructor.lua
>              local row <const> = rows[1]
see upper change query to single

2022-06-07 18:32 UTC, MoskalykA requested changes

2022-06-07 18:32 UTC, MoskalykA commented on src/core/events/client/revive.lua
> +end)
```suggestion
NCS:registerNetEvent("ncs_core:revivePlayer")
NCS:handleEvent("ncs_core:revivePlayer", function(coords, skin)
    API_Player:spawn(coords)

    CreateThread(function()
        Wait(100)

        MOD_Skin:applySkin(skin)
    end)
end)
```

2022-06-07 18:32 UTC, MoskalykA commented on src/modules/commands/server/revivePlayer.lua
> +    NCS:triggerClientEvent("ncs_core:revivePlayer", target.serverId, formattedCoords)
```suggestion
    NCS:triggerClientEvent("ncs_core:revivePlayer", target.serverId, formattedCoords, target.character.skin)
```

2022-06-07 18:32 UTC, MoskalykA commented on src/modules/players/server/events/onPlayerDeath.lua
> +                NCSCharacter:setDeathStatus(_src, isDead, playerDeathData)
```suggestion
                if sourceKillerEntity ~= _src and sourceKillerEntity  ~= 0 then
                    local playerDeathData = {
                        ["playerDeathCoords"] = playerDeathCoords,
                        ["playerDeathCause"] = sourceDeathCause,
                        ["playerDeathTime"] = GetGameTimer(),
                        ["killerEntity"] = sourceKillerEntity
                    }
                    NCS:trace(("Player id ^2%s ^7(^2%s^7) as been killed by ^2%s ^7(^2%s^7)"):format(_src, MOD_Players:get(_src).name, sourceKillerEntity, MOD_Players:get(sourceKillerEntity).name), 3)
                    NCSCharacter:setDeathStatus(_src, isDead, playerDeathData)
                else
                    local playerDeathData = {
                        ["playerDeathCoords"] = playerDeathCoords,
                        ["playerDeathCause"] = sourceDeathCause,
                        ["playerDeathTime"] = GetGameTimer(),
                        ["killerEntity"] = false
                    }
                    NCS:trace(("Player id ^2%s ^7(^2%s^7) died without killer"):format(_src, MOD_Players:get(_src).name), 3)
                    NCSCharacter:setDeathStatus(_src, isDead, playerDeathData)
                end
```

2022-06-07 18:54 UTC, MoskalykA requested changes

2022-06-07 18:54 UTC, MoskalykA commented on src/modules/players/server/events/onPlayerDeath.lua
> +end)
```suggestion
```

2022-06-07 21:28 UTC, LQuatre commented
is not functions, is Events*

2022-06-07 22:36 UTC, LQuatre commented
PLEASE LAST REVIEW 👍 
I don't have any ideas for additions on this module

2022-06-09 21:13 UTC, ach-git commented
I thinks for replace the Wait(5000) when in game you can use src/modules/skin/client/events/onInitializeCharacter.lua:12&18
add: 
```lua
NCS:triggerEvent("initializedCharacter")
```
and replace "nowInGame" by "initializedCharacter"

2022-06-09 22:16 UTC, LQuatre commented
> I thinks for replace the Wait(5000) when in game you can use src/modules/skin/client/events/onInitializeCharacter.lua:12&18 add:
> 
> ```lua
> NCS:triggerEvent("initializedCharacter")
> ```
> 
> and replace "nowInGame" by "initializedCharacter"

New event ?

2022-06-12 16:57 UTC, MoskalykA approved these changes

2022-06-12 16:57 UTC, merged