Commands SpawnCar
NextCitizens/ncs_core pull request #182
Opened 2022-06-07 20:56 UTC by Barwoz

2022-06-07 21:04 UTC, CsokiHUN requested changes

2022-06-07 21:04 UTC, CsokiHUN commented on src/core/events/client/car.lua
> +    API_Ped:setIntoVehicle(GetPlayerPed(-1), vehicle, -1)
```suggestion
     API_Ped:setIntoVehicle(PlayerPedId(), vehicle, -1)
```

2022-06-07 22:04 UTC, LQuatre commented on src/core/events/client/car.lua
> +    API_Ped:setIntoVehicle(GetPlayerPed(-1), vehicle, -1)
it's same result

2022-06-08 05:30 UTC, MoskalykA requested changes
Syntax to be reviewed (please see the core syntax in general) and the logic (a server side function exists to display a vehicle: https://github.com/NextCitizens/ncs_core/blob/main/src/api/vehicles/server/spawnVehicle.lua)

2022-06-08 05:36 UTC, Barwoz commented
> Syntax to be reviewed (please see the core syntax in general) and the logic (a server side function exists to display a vehicle: https://github.com/NextCitizens/ncs_core/blob/main/src/api/vehicles/server/spawnVehicle.lua)

Yes I have used this server side function. For syntax yes I am sorry, I will check it out and edit.

2022-06-08 11:04 UTC, CsokiHUN requested changes

2022-06-08 11:04 UTC, CsokiHUN commented on src/localization/locales/lang_hu.lua
> +    SUCCESS_CAR_SPAWNED = "A jármű elindult.",
```suggestion
    SUCCESS_CAR_SPAWNED = "Sikeres jármű lehívás.",
```

2022-06-08 12:41 UTC, LQuatre commented
> Syntax to be reviewed (please see the core syntax in general) and the logic (a server side function exists to display a vehicle: https://github.com/NextCitizens/ncs_core/blob/main/src/api/vehicles/server/spawnVehicle.lua)

ServerSide functions is broken ://

2022-06-12 16:56 UTC, MoskalykA commented
Waiting for the redesign of the server-side vehicle system

2022-06-12 16:56 UTC, closed without merging