:zap: Create inventory system
NextCitizens/ncs_core pull request #196
Opened 2022-06-26 16:56 UTC by utopi160

2022-06-26 21:57 UTC, CsokiHUN approved these changes

2022-06-28 21:09 UTC, CsokiHUN requested changes

2022-06-28 21:09 UTC, CsokiHUN commented on src/enum/accountsType.lua
> +    local displayAccount = { [1] = _Literals.CASH_MONEY, [3] = _Literals.BLACK_MONEY }
```suggestion
    local displayAccount <const> = { [1] = _Literals.CASH_MONEY, [3] = _Literals.BLACK_MONEY }
  ```

2022-06-29 08:10 UTC, CsokiHUN approved these changes

2022-06-30 15:18 UTC, ach-git commented
**Hello**, good PR but why did you delete character account ? (I think it's because it's not already done but I want to know yours reason)

2022-06-30 15:46 UTC, utopi160 commented
> **Hello**, good PR but why did you delete character account ? (I think it's because it's not already done but I want to know yours reason)

Hi, I thought it was easier to order everything in the same table.

2022-07-03 19:25 UTC, merged