:sparkles: : Create Discord API
NextCitizens/ncs_core pull request #66
Opened 2022-05-28 09:26 UTC by utopi160

2022-05-28 09:36 UTC, MoskalykA commented
I should delete the webhook part of my pr and we would be complementary?

2022-05-28 09:36 UTC, MoskalykA commented
https://github.com/NextCitizens/ncs_core/pull/58

2022-05-28 09:48 UTC, PABLO-1610 commented
> #58

The interesting thing is that his part is more focused on server-side (interaction with a Discord Bot etc) but your is more focused on the client one (Rich presence (...)), i think i will add your functions to this PR.

2022-05-28 09:49 UTC, MoskalykA commented
> > #58
> 
> The interesting thing is that his part is more focused on server-side (interaction with a Discord Bot etc) but your is more focused on the client one (Rich presence (...)), i think i will add your functions to this PR.

I'll just delete the webhook part in this case

2022-05-28 09:50 UTC, utopi160 commented
Yess !
I'm sorry, I hadn't seen your pull request ....

2022-05-28 09:51 UTC, MoskalykA commented
I have deleted my webhooks part

2022-05-28 09:51 UTC, MoskalykA commented
> Yess ! I'm sorry, I hadn't seen your pull request ....

No, that's good. There is a full api

2022-05-28 10:03 UTC, PABLO-1610 commented
Hm, seems pretty good but, i think it could be better if we could have many instance of bot, in case of you need at least 2 bots doing 2 satisfying two differents things.

I recommand creating an object of DiscordBot, which will contains all functions related to it (eg: send message, retrieve users in guild etc.), the only parameter which will be passed through the constructor should be the bot token (it's really more secured than having it defined by "`API_Discord.token = "..."` .

Tell me what you guys think about this @MoskalykA @utopi160

2022-05-28 10:09 UTC, utopi160 commented
Mummm i see but how to organize the exports ?

> Hm, seems pretty good but, i think it could be better if we could have many instance of bot, in case of you need at least 2 bots doing 2 satisfying two differents things.
> 
> I recommand creating an object of DiscordBot, which will contains all functions related to it (eg: send message, retrieve users in guild etc.), the only parameter which will be passed through the constructor should be the bot token (it's really more secured than having it defined by "`API_Discord.token = "..."` .
> 
> Tell me what you guys think about this @MoskalykA @utopi160

2022-05-28 10:11 UTC, MoskalykA commented
> Mummm i see but how to organize the exports ?

Yes object-oriented code

2022-05-28 10:11 UTC, MoskalykA commented
> Mummm i see but how to organize the exports ?
> 
> > Hm, seems pretty good but, i think it could be better if we could have many instance of bot, in case of you need at least 2 bots doing 2 satisfying two differents things.
> > I recommand creating an object of DiscordBot, which will contains all functions related to it (eg: send message, retrieve users in guild etc.), the only parameter which will be passed through the constructor should be the bot token (it's really more secured than having it defined by "`API_Discord.token = "..."` .
> > Tell me what you guys think about this @MoskalykA @utopi160

I don't really know what you want?

2022-05-28 10:14 UTC, PABLO-1610 commented
@utopi160 take a look at : https://github.com/NextCitizens/ncs_core/tree/main/src/modules/players/server

You should create a new module and **then** a simple api which can interact with the module.

2022-05-28 10:14 UTC, utopi160 commented
> You should create a new module and **then** a simple api which can interact with the module.

Ok thank you !

2022-05-28 12:25 UTC, utopi160 commented
I don't really see how the API is organized ?
![image](https://user-images.githubusercontent.com/93077305/170825440-ee7ed087-f460-4657-bcb7-784ee2b4e95b.png)

2022-05-28 13:37 UTC, MoskalykA commented
> I don't really see how the API is organized ? ![image](https://user-images.githubusercontent.com/93077305/170825440-ee7ed087-f460-4657-bcb7-784ee2b4e95b.png)

You should make an object-oriented structure in this style:
![ob](https://user-images.githubusercontent.com/100430077/170827888-2c15b029-d9d1-4b78-bbf2-c34c44a4eb4a.png)

2022-05-28 13:40 UTC, utopi160 commented
But it's not okay ?
https://github.com/utopi160/ncs_core/tree/main/src/class/Bot/server
https://github.com/utopi160/ncs_core/tree/main/src/modules/bot

2022-05-28 13:42 UTC, MoskalykA commented
> But it's not okay ? https://github.com/utopi160/ncs_core/tree/main/src/class/Bot/server https://github.com/utopi160/ncs_core/tree/main/src/modules/bot

That's good, you could also make a file by function

2022-05-28 13:44 UTC, utopi160 commented
But I don't see how to relate to API_DiscordBot, an idea ?

2022-05-28 13:52 UTC, MoskalykA commented
> But I don't see how to relate to API_DiscordBot, an idea ?

![image](https://user-images.githubusercontent.com/100430077/170828355-d6041c71-b1f4-4212-b685-3dbd5c3191b9.png)
I would have done a bit like that but I would have put:
    Bot = NCSBot
    Bots = MOD_Bots

2022-05-28 13:54 UTC, utopi160 commented
Ok thank you !!

> > But I don't see how to relate to API_DiscordBot, an idea ?
> 
> ![image](https://user-images.githubusercontent.com/100430077/170828355-d6041c71-b1f4-4212-b685-3dbd5c3191b9.png) I would have done a bit like that but I would have put: Bot = NCSBot Bots = MOD_Bots

2022-05-28 15:09 UTC, MoskalykA requested changes

2022-05-28 15:09 UTC, MoskalykA commented on src/class/Bot/server/NCSBot.lua
> +    end
```suggestion
    if (player and player.avatar) then
        if (player.avatar:sub(2, 2) == "_") then -- Determine if the avatar is PNG or GIF
            return ("https://cdn.discordapp.com/avatars/%s/%s.gif"):format(discordId, player.avatar)
        else
            return ("https://cdn.discordapp.com/avatars/%s/%s.png"):format(discordId, player.avatar)
        end
    else
        return ("https://cdn.discordapp.com/embed/avatars/0.png")
    end
```

2022-05-28 15:09 UTC, MoskalykA commented on src/class/Bot/server/NCSBot.lua
> +---@return table
```suggestion
---get_guild
---@param guildId string
---@public
---@return table
```

2022-05-28 15:09 UTC, MoskalykA commented on src/class/Bot/server/NCSBot.lua
> +---@return table
```suggestion
---@return number
```

2022-05-28 15:09 UTC, MoskalykA commented on src/class/Bot/server/NCSBot.lua
> +---@return table
```suggestion
---@return number
```

2022-05-28 15:09 UTC, MoskalykA commented on src/class/Bot/server/NCSBot.lua
> +---@return table
```suggestion
---@return number
```

2022-05-28 15:09 UTC, MoskalykA commented on src/class/Bot/server/NCSBot.lua
> +    end
```suggestion
    if (guild and guild.icon) then
        if (guild.icon:sub(2, 2) == "_") then -- Determine if the icon is PNG or GIF
            return ("https://cdn.discordapp.com/icons/%s/%s.gif"):format(guildId, guild.icon)
        else
            return ("https://cdn.discordapp.com/icons/%s/%s.png"):format(guildId, guild.icon)
        end
    else
        return ("https://cdn.discordapp.com/embed/avatars/0.png")
    end
```

2022-05-29 13:14 UTC, utopi160 commented
It's not OK ?

2022-05-29 19:53 UTC, PABLO-1610 approved these changes
Awesome PR 🤩 Thanks a lot

2022-05-29 19:54 UTC, merged