✨ Create Blip
NextCitizens/ncs_core pull request #75
Opened 2022-05-28 14:47 UTC by Walker974

Hi , I made sure to create blip in server side .
I did'nt find any other solution.

2022-05-28 14:56 UTC, MoskalykA requested changes

2022-05-28 14:56 UTC, MoskalykA commented on src/api/blip/server/createBlip.lua
> +---@public
```suggestion
---create Blip
---@param blip_name string
---@param blip_coords table
---@param blip_sprite number
---@param blip_display number
---@param blip_color number
---@param blip_scale number
---@return void
---@public
```

2022-05-28 14:56 UTC, MoskalykA commented on src/api/blip/client/customBlip.lua
> +    Blip = AddBlipForCoord(blip_coords.x, blip_coords.y, blip_coords.z)
```suggestion
    local Blip = AddBlipForCoord(blip_coords.x, blip_coords.y, blip_coords.z)
```

2022-05-28 15:01 UTC, Walker974 commented
good now ?

2022-05-28 15:11 UTC, MoskalykA requested changes

2022-05-28 15:11 UTC, MoskalykA commented on src/api/blip/client/customBlip.lua
> +end)
```suggestion
_NCS:registerNetEvent('API_Blip:customBlip')
_NCS:handleEvent('API_Blip:customBlip', function(blip_name, blip_coords, blip_sprite, blip_display, blip_scale, blip_color)
    local Blip = AddBlipForCoord(blip_coords.x, blip_coords.y, blip_coords.z)
    SetBlipSprite(Blip, blip_sprite)
    SetBlipDisplay(Blip, blip_display)
    SetBlipScale(Blip, blip_scale)
    SetBlipColour(Blip, blip_color)

    SetBlipAsShortRange(Blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString(blip_name)
    EndTextCommandSetBlipName(Blip)
end)
```

2022-05-28 15:11 UTC, MoskalykA commented on src/api/blip/server/createBlip.lua
> +end
```suggestion
---createBlip
---@param blip_name string
---@param blip_coords table
---@param blip_sprite number
---@param blip_display number
---@param blip_color number
---@param blip_scale number
---@return void
---@public
function API_Blip:createBlip(blip_name, blip_coords, blip_sprite, blip_display, blip_scale, blip_color)
    _NCS:triggerClientEvent('API_Blip:customBlip', -1, blip_name, blip_coords, blip_sprite, blip_display, blip_scale, blip_color)
end
```

2022-05-28 15:49 UTC, Walker974 commented
good ?

2022-05-28 15:58 UTC, MoskalykA approved these changes

2022-05-29 05:24 UTC, Wisfakim commented
Maybe you can add blip management list at client side ? In case if you want remove blip ? ( exemple for a job)

2022-05-29 09:20 UTC, MoskalykA commented
> Maybe you can add blip management list at client side ? In case if you want remove blip ? ( exemple for a job)

It would be enough to make a global variable on the client side and to assign the blips to this variable with an id. After that, you would have to make a function that takes the id as a parameter and deletes the blip from the table.
@Walker974 you want to do this feature?

2022-05-29 09:27 UTC, MoskalykA commented
> Maybe you can add blip management list at client side ? In case if you want remove blip ? ( exemple for a job)

It would be enough to make a global variable on the client side and to assign the blips to this variable with an id. After that, you would have to make a function that takes the id as a parameter and deletes the blip from the table.

2022-05-29 09:29 UTC, MoskalykA commented
Sorry but Pablo is going to import one of his systems that will handle zones, blips and npcs.
Thanks for your contribution and for the future try to make less commits but also use the gitmoji conventions. (https://gitmoji.dev/)

2022-05-29 09:29 UTC, closed without merging