✏️ #API_Vehicles update function & news
NextCitizens/ncs_core pull request #97
Opened 2022-05-30 17:03 UTC by K4VK4Z

Create new functions : 

```lua
local vehicleFuel = API_Vehicles:getFuelTank(vehicleId) -- return fuel tank

local vehicleSpeed = API_Vehicles:getSpeed(vehicleId) -- return vehicle speed in km/h

API_Vehicles:setFuel(vehicleId, fuel -- Int value) 
```

2022-05-30 17:10 UTC, MoskalykA requested changes

2022-05-30 17:10 UTC, MoskalykA commented on src/api/vehicles/client/setFuel.lua
> +
```suggestion
---setFuel
---@param vehicleId number
---@param fuel number
---@return number
---@public
function API_Vehicles:setFuel(vehicleId, fuel)
    if (vehicleId) then
        SetVehicleFuelLevel(vehicleId, fuel)
    end
    _NCS:trace('Unable to find vehicle', 1)
end
```

2022-05-30 17:10 UTC, MoskalykA commented on src/api/vehicles/client/getSpeed.lua
> +
```suggestion
---getSpeed
---@param vehicleId number
---@return number
---@public
function API_Vehicles:getSpeed(vehicleId)
    if (vehicleId) then
        local speed <const> = (GetEntitySpeed(vehicleId) * 3.6) --Set speed to km/h
        return speed
    end
    _NCS:trace('Unable to find vehicle', 1)
end
```

2022-05-30 17:10 UTC, MoskalykA commented on src/api/vehicles/client/getFuelTank.lua
> +end
```suggestion
---getFuelTank
---@param vehicleId number
---@return number
---@public
function API_Vehicles:getFuelTank(vehicleId)
    if (vehicleId) then
        local fuel <const> = GetVehicleHandlingFloat(vehicleId, "CHandlingData", "fPetrolTankVolume")
        return fuel
    end
    _NCS:trace('Unable to find vehicle', 1)
end
```

2022-05-30 18:29 UTC, MoskalykA requested changes

2022-05-30 18:29 UTC, MoskalykA commented on src/api/objects/server/createObject.lua
>  ---@return void
Wrong type

2022-05-30 18:29 UTC, MoskalykA commented on src/api/ped/server/spawnPed.lua
>  ---@return void
Wrong type

2022-05-30 18:29 UTC, MoskalykA commented on src/api/vehicles/client/getFuelTank.lua
> +    _NCS:trace('Unable to find vehicle', 1)
Use " please

2022-05-30 18:29 UTC, MoskalykA commented on src/api/vehicles/client/getSpeed.lua
> +    _NCS:trace('Unable to find vehicle', 1)
Use " please

2022-05-30 18:29 UTC, MoskalykA commented on src/api/vehicles/client/setFuel.lua
> +    _NCS:trace('Unable to find vehicle', 1)
Use " please

2022-05-30 23:27 UTC, K4VK4Z commented
**Hi!** 
_Modifications have been made & add/modification of divers api functions_

2022-05-31 15:44 UTC, MoskalykA requested changes
There are lots of indentation errors, please correct this.

2022-05-31 15:44 UTC, MoskalykA commented on src/api/ped/client/getDistance.lua
> +end
```suggestion
---getDistance
---@param pedId number
---@param coords table
---@return distance
---@public
function API_Player:getDistance(pedId, coords)
    local distance <const> =  #(API_Ped:getPosition(pedId) - coords)
    return distance
end
```

2022-05-31 16:22 UTC, MoskalykA commented on src/api/vehicles/client/getVehicleProperties.lua
```suggestion
```

2022-05-31 16:22 UTC, MoskalykA commented on src/api/vehicles/client/getVehicleProperties.lua
>  function API_Vehicles:getProperties(vehicleEntity)
vehicleEntity -> vehicleId

2022-05-31 16:23 UTC, MoskalykA commented on src/api/vehicles/client/setVehicleProperties.lua
> +		if type(props.color1) == 'number' then
' -> "

2022-05-31 17:04 UTC, MoskalykA requested changes

2022-05-31 17:04 UTC, MoskalykA commented on src/api/vehicles/client/setVehicleProperties.lua
>      local colorPrimary, colorSecondary = GetVehicleColours(vehicleEntity)
Review syntax and variable name

2022-05-31 21:40 UTC, merged